name: checks linter
run-name: ${{ github.actor }} linter Actions
on: [push]
jobs:
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - run: npm run lint
